[build]
  publish = "."

# Optimize MEI file serving
[[headers]]
  for = "/*.mei"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

# Optimize JSON mapping files
[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=86400"

# Optimize static assets
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Enable compression for all text files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirect rules (if needed)
[[redirects]]
  from = "/Spanish/*"
  to = "/Spanish_part_:splat"
  status = 301
  force = false
